# Environment setting
環境設定

In [1]:
import os
import requests
from pathlib import Path


# determine branch, default is main
branch = "main"

# Check if running in Google Colab
is_colab = "COLAB_GPU" in os.environ

if is_colab:
    # Download the utils.py file from GitHub
    utils_url = (
        f"https://raw.githubusercontent.com/nics-tw/petsard/{branch}/demo/utils.py"
    )
    response = requests.get(utils_url)

    if response.status_code == 200:
        # Save the utils.py file
        with open("utils.py", "w") as f:
            f.write(response.text)

        # Create an empty __init__.py
        Path("__init__.py").touch()
    else:
        raise RuntimeError(
            f"Failed to download utils.py. Status code: {response.status_code}"
        )

In [ ]:
# Now import and run the setup
from utils import (
    get_yaml_path,
    setup_environment,
)


setup_environment(
    is_colab,
    branch,
    benchmark_data=[
        "adult-income",
    ],
)

In [3]:
from petsard import Executor

# YAML Configuration for PETsARD
PETsARD 的 YAML 設定

## Default Synthesis
預設合成

In [4]:
yaml_file_case: str = "default-synthesis.yaml"

yaml_path_case: str = get_yaml_path(
    is_colab=is_colab,
    yaml_file=yaml_file_case,
    branch=branch,
)

Configuration content:
---
Loader:
  data:
    filepath: 'benchmark/adult-income.csv'
Preprocessor:
  demo:
    method: 'default'
Synthesizer:
  demo:
    method: 'default' # sdv-single_table-gaussiancopula
Postprocessor:
  demo:
    method: 'default'
Reporter:
  output:
    method: 'save_data'
    source: 'Postprocessor'
...

### Execution and Result
執行與結果

In [5]:
# Initialize and run executor
exec_case = Executor(config=yaml_path_case)
exec_case.run()

Now is petsard_Loader[data]_Preprocessor[demo]_Synthesizer[demo]_Postprocessor[demo] save to csv...

In [7]:
exec_case.get_result()[
    "Loader[data]_Preprocessor[demo]_Synthesizer[demo]_Postprocessor[demo]_Reporter[output]"
]["Loader[data]_Preprocessor[demo]_Synthesizer[demo]_Postprocessor[demo]"]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,45.512893,Local-gov,105689.955677,HS-grad,12.105632,Never-married,Transport-moving,Husband,White,Female,0.0,0.0,38.749747,United-States,<=50K
1,30.499560,Private,142167.749168,Bachelors,9.944627,Married-civ-spouse,Protective-serv,Husband,Black,Male,0.0,0.0,35.750809,United-States,>50K
2,30.666088,Self-emp-inc,70682.239701,Some-college,11.984635,Never-married,Exec-managerial,Unmarried,White,Female,0.0,0.0,35.629287,United-States,<=50K
3,35.605122,Private,217418.314592,Masters,8.728909,Never-married,?,Not-in-family,White,Male,0.0,0.0,36.473108,Canada,<=50K
4,31.010978,Private,85353.960525,Some-college,11.887584,Never-married,Other-service,Husband,White,Female,0.0,0.0,51.820506,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28553,45.744612,Private,204517.687124,HS-grad,10.556457,Married-civ-spouse,Transport-moving,Husband,White,Male,0.0,0.0,50.428579,United-States,<=50K
28554,40.147268,Private,215714.871541,HS-grad,8.935876,Divorced,Exec-managerial,Husband,White,Male,0.0,0.0,47.407423,United-States,<=50K
28555,37.076593,Private,300336.570022,Bachelors,11.688682,Divorced,Prof-specialty,Unmarried,Asian-Pac-Islander,Male,0.0,0.0,51.664408,United-States,<=50K
28556,20.479046,Private,283649.417044,Bachelors,12.262469,Widowed,Craft-repair,Own-child,White,Female,0.0,0.0,34.931739,United-States,<=50K
28557,33.254965,Private,117875.907551,Assoc-voc,11.186968,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.865096,United-States,<=50K